### ISSUE TITLE
LeafGL Nationwide Map

### ISSUE THREAD

**Issue by andrew-vancil** [geomarker-io/dep_index#9]
I've run into some issues embedding the nationwide Dep Index map on the Readme. It looks like .md files don't really support html widgets and I can't find any workarounds, so I've thought of a couple other options:
- Leave as is
- I made a .rmd version of the Readme with an html output that includes the interactive map. Is there any way use that as the Readme?
  - Would it be worthwhile to reorganize the geomarkers list into a github website with the index and all that? We could use the html file as the dep index page
- Leave the static map on the Readme, but make it a clickable link that goes to the interactive map hosted on Shinyapps.io

I think I would vote for the third option if we can't redirect to the working .rmd output, but I'm game for the others or a different approach.

**Comment by cole-brokamp** [comment]
Yes, we can include an html file in the repository for the map and then set up a better way to host this on github pages than we have now.  Right now, we are using the simple option of using the README as the homepage, but can setup a whole branch or folder to create a website instead.  

Can you push up the Rmd and html file to a separate branch? and then we can think about how to best deploy the site from there through a pull request.

**Comment by andrew-vancil** [comment]
Sounds like a plan - just started the pull request

**Comment by cole-brokamp** [comment]
I think I've got it working, but the html map is just too large to push to github (~128 MB and limit is 100 MB).  Trying to work on something to push up soon.  After that, we will still need to add a legend to the map and the possibility to use other basemap layers.

**Comment by cole-brokamp** [comment]
i pulled this out into #11 and ended up hosting the map on its own s3 bucket as a website at: http://dep-index.s3-website.us-east-2.amazonaws.com/
